name: OpenItem
main: com.lithium3141.OpenItem.OpenItem
author: lithium3141
version: 1.0-alpha (rev @BUILD@)
database: false
commands:
    give:
        description: Give a player items
        usage: /<command>
